import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'ltr' | 'rtl';
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    'nav.home': 'Home', 'nav.services': 'Services', 'nav.about': 'About', 'nav.faq': 'FAQ', 'nav.language': 'العربية',
    'hero.slide1.title': 'Delivering Excellence in Oil Services & Energy Solutions.', 'hero.slide1.subtitle': 'Integrated storage, logistics, and consulting for the oil & gas sector.', 'hero.slide1.cta': 'Get Started',
    'hero.slide2.title': 'Why Petra?', 'hero.slide2.subtitle': 'Because we combine deep expertise with operational integrity and precision.', 'hero.slide2.cta': 'Discover Why',
    'hero.slide3.title': 'Quality & Safety in Every Operation', 'hero.slide3.subtitle': 'We follow strict international standards to ensure reliability and risk-free performance.', 'hero.slide3.cta': 'See Our Standards',
    'hero.slide4.title': 'Our Reach, Your Advantage', 'hero.slide4.subtitle': 'Comprehensive logistics and sustainable initiatives across the energy sector.', 'hero.slide4.cta': 'Explore Services',
    'quicklinks.faq.title': 'FAQs', 'quicklinks.faq.desc': 'Learn more about our services, procedures, and safety standards through the most frequently asked questions.', 'quicklinks.faq.cta': 'View FAQs',
    'quicklinks.contact.title': 'Contact Us', 'quicklinks.contact.desc': 'Our team is ready to assist you. Reach out for inquiries, partnerships, or service requests.', 'quicklinks.contact.cta': 'Get in Touch',
    'quicklinks.safety.title': 'Safety & Compliance', 'quicklinks.safety.desc': 'We apply rigorous safety measures to ensure the protection of people, assets, and the environment.', 'quicklinks.safety.cta': 'Safety Commitment',
    'services.title': 'Innovative Services That Power the Future of Energy', 'services.subtitle': 'Comprehensive solutions for the modern energy sector', 'services.cta.title': 'Ready to enhance your energy operations?', 'services.cta.button': 'Contact Our Team',
    'detailed.storage.title': 'Petroleum Derivatives Storage', 'detailed.storage.desc': 'We provide highly secure and efficient storage solutions for gasoline, diesel, oil, and other petroleum derivatives. Our operations include management and maintenance of storage tanks in accordance with international safety and quality standards. Inventory monitoring systems reduce product loss and improve operational control.', 'detailed.storage.cta': 'Learn More',
    'detailed.logistics.title': 'Supply Chain Management', 'detailed.logistics.desc': 'We plan and execute integrated logistics solutions for transporting and distributing petroleum derivatives. Designed to optimize distribution networks, reduce operational costs, and ensure timely delivery. We maintain strong relationships with suppliers and clients to secure supply continuity.', 'detailed.logistics.cta': 'Explore Logistics',
    'detailed.station.title': 'Fuel Station Investment & Operations', 'detailed.station.desc': 'Feasibility studies for establishing and upgrading fuel stations in strategic locations. Full operation and management services focused on long-term profitability. Support for sustainable initiatives including solar-powered energy solutions.', 'detailed.station.cta': 'See Opportunities',
    'detailed.consulting.title': 'Technical & Engineering Consultancy', 'detailed.consulting.desc': 'Expert consulting solutions for oil & gas infrastructure development. Market analysis and identification of new investment opportunities in the petroleum sector. Training programs that develop qualified teams capable of managing critical petroleum facilities.', 'detailed.consulting.cta': 'Get Consultation',
    'service.dropdown.storage': 'Petroleum Products Storage', 'service.dropdown.logistics': 'Supply Chain Management', 'service.dropdown.station': 'Fuel Station Investment', 'service.dropdown.consulting': 'Technical & Engineering Consulting',
    'about.title': 'Who We Are', 'about.description': 'Petra is a specialized company in the management, storage, and logistics of petroleum derivatives. We work with industry-leading standards to ensure safe, reliable, and efficient energy solutions that support national growth and business continuity.',
    'about.vision.title': 'Our Vision', 'about.vision.text': 'To be a trusted leader in petroleum logistics and storage services.', 'about.mission.title': 'Our Mission', 'about.mission.text': 'To deliver energy with excellence through innovation, safety, and operational efficiency.',
    'about.values.title': 'Our Core Values', 'about.values.safety': 'Safety', 'about.values.reliability': 'Reliability', 'about.values.integrity': 'Integrity', 'about.values.sustainability': 'Sustainability', 'about.values.excellence': 'Excellence',
    'safety.title': 'Safety First. Quality Always.', 'safety.description': 'We apply strict HSE (Health, Safety, and Environment) standards across every stage of our operations. Our safety protocols protect employees, assets, and the environment — while maintaining compliance with global regulations and industry certifications.',
    'safety.hse': 'Health, Safety & Environment', 'safety.highlight1': 'Preventive maintenance and risk control', 'safety.highlight2': 'Emergency response readiness', 'safety.highlight3': 'Environmental protection practices',
    'projects.title': 'Our Track Record', 'projects.description': 'We take pride in delivering successful logistics and storage solutions for various strategic clients in the oil & gas sector. Petra continues to grow with new development and investment projects across the region.',
    'projects.stats.years': 'Years of Experience', 'projects.stats.clients': 'Satisfied Clients', 'projects.stats.locations': 'Service Locations', 'projects.stats.certifications': 'Certifications',
    'projects.project1.tag': 'Storage', 'projects.project1.title': 'Regional Storage Facility', 'projects.project1.desc': 'State-of-the-art petroleum storage facility with 50,000+ barrel capacity.',
    'projects.project2.tag': 'Logistics', 'projects.project2.title': 'Fleet Optimization Project', 'projects.project2.desc': 'Comprehensive logistics overhaul reducing delivery times by 40%.',
    'projects.project3.tag': 'Investment', 'projects.project3.title': 'Green Fuel Stations', 'projects.project3.desc': 'Solar-powered fuel station network across strategic locations.',
    'contact.title': 'Get In Touch', 'contact.description': 'Our team is ready to support your needs. Connect with us for business inquiries, service proposals, or partnership opportunities.',
    'contact.form.name': 'Full Name', 'contact.form.email': 'Email Address', 'contact.form.phone': 'Phone Number', 'contact.form.message': 'Your Message', 'contact.form.submit': 'Send Message', 'contact.form.success': 'Message Sent!', 'contact.form.successDesc': 'We will get back to you shortly.',
    'contact.info.phone': 'Phone', 'contact.info.email': 'Email', 'contact.info.address': 'Address', 'contact.info.hours': 'Working Hours', 'contact.map.placeholder': 'Location Map',
    'cta.title': 'Partner with Us to Power the Future', 'cta.description': 'Ready to take your energy operations to the next level? Let us help you achieve excellence in petroleum storage, logistics, and consulting.', 'cta.button1': 'Request a Quote', 'cta.button2': 'Learn More',
    'faq.title': 'Frequently Asked Questions', 'faq.subtitle': 'Find answers to common questions about our services and operations.',
    'faq.q1': 'What services does Petra offer?', 'faq.a1': 'Petra offers comprehensive petroleum services including storage solutions, supply chain management, fuel station investment & operations, and technical & engineering consultancy.',
    'faq.q2': 'What safety standards do you follow?', 'faq.a2': 'We adhere to strict international HSE standards, ensuring all operations comply with global regulations and industry best practices.',
    'faq.q3': 'Where are your services available?', 'faq.a3': 'Our services are available across Jordan and the broader Middle East region.',
    'faq.q4': 'How can I request a quote?', 'faq.a4': 'You can request a quote by filling out our contact form, calling our office directly, or sending us an email.',
    'faq.q5': 'Do you offer partnership opportunities?', 'faq.a5': 'Yes, we actively seek strategic partnerships with companies in the oil & gas sector.',
    'faq.q6': 'What makes Petra different from competitors?', 'faq.a6': 'Petra combines deep industry expertise with operational integrity, innovative solutions, and a commitment to safety and sustainability.',
    'footer.description': 'Specialized in petroleum derivatives management, storage, and logistics.', 'footer.quickLinks': 'Quick Links', 'footer.services': 'Our Services', 'footer.contact': 'Contact Info',
    'footer.links.home': 'Home', 'footer.links.services': 'Services', 'footer.links.about': 'About Us', 'footer.links.contact': 'Contact', 'footer.rights': 'All rights reserved.',
    // About Page
    'about.hero.title': 'Petra — Strength… Resilience… Stability in the Energy World',
    'about.hero.subtitle': 'A leading company in petroleum derivatives storage, transportation, and consulting services.',
    'about.hero.cta1': 'Contact Us',
    'about.hero.cta2': 'Our Services',
    'about.section.label': 'About Us',
    'about.section.title': 'Who We Are',
    'about.section.paragraph1': 'The word Petra means "rock" in ancient Greek, symbolizing strength, resilience, patience, and stability. Petra Oil Services is a leading company in the oil and energy sector, offering extensive expertise in providing integrated solutions for storage, transportation, and consulting.',
    'about.section.paragraph2': 'The company\'s scope includes oil & gas consulting, petroleum product storage and transport (land & sea), fuel station investment and rehabilitation, supply and installation of fuel systems, and various services related to the oil and gas industry.',
    'timeline.label': 'Our Journey',
    'timeline.title': 'Company Timeline',
    'timeline.2019': 'Company established in the local market. Strategic planning and infrastructure development. Obtaining required licenses and forming a specialized team.',
    'timeline.2020': 'Strategic expansion and doubling storage capacity. Operational efficiency improvements and workforce training.',
    'timeline.2022': 'Implementation of advanced monitoring technologies. Adoption of FMS (Fuel Management System). Achieving high safety records and operational excellence.',
    'timeline.2024': 'Strengthening the company\'s position as a fuel-solutions leader. Expansion into oil consulting services. Building strong market reputation as a trusted partner.',
    'timeline.2025': 'Received international quality certifications: ISO 9001 and ISO 29001.',
    'vision.title': 'Our Vision',
    'vision.text': 'To become the leading provider of petroleum derivative services by delivering high-quality solutions that support energy sustainability and exceed client expectations.',
    'mission.title': 'Our Mission',
    'mission.text': 'To provide safe and efficient storage and service solutions for petroleum products while maintaining the highest standards of quality, safety, and environmental sustainability.',
    'scope.label': 'What We Do',
    'scope.title': 'Scope of Work',
    'scope.storage.title': 'Petroleum Storage',
    'scope.storage.desc': 'Safe and efficient storage solutions for gasoline, diesel, oil, and other products. Operation and management of storage tanks according to global standards. Inventory monitoring and loss-reduction technologies.',
    'scope.logistics.title': 'Supply Chain Management',
    'scope.logistics.desc': 'Planning and executing integrated logistics for petroleum product distribution. Optimizing distribution networks to reduce costs and improve efficiency. Managing supplier and customer relationships for uninterrupted supply.',
    'scope.station.title': 'Fuel Station Investment',
    'scope.station.desc': 'Feasibility studies for new or existing fuel stations. Operation and management with high profitability standards. Development of alternative energy solutions such as solar power systems.',
    'scope.consulting.title': 'Technical & Consulting Services',
    'scope.consulting.desc': 'Engineering and technical consulting for oil and gas projects. Market analysis and investment opportunity studies. Training teams on industry best practices and operational excellence.',
    'values.label': 'What We Believe',
    'values.title': 'Our Values',
    'values.comprehensive': 'Commitment to delivering comprehensive, integrated petroleum storage and distribution solutions.',
    'values.technology': 'Use of advanced technologies and global best practices for maximum quality and efficiency.',
    'values.safety': 'Adherence to the highest safety and quality standards.',
    'values.improvement': 'Continuous improvement through expert teams and evolving market understanding.',
    'values.innovation': 'Providing innovative solutions that meet and exceed client expectations.',
    'about.cta.title': 'Ready to Partner with Us?',
    'about.cta.description': 'Let us help you achieve excellence in petroleum storage, logistics, and consulting.',
    'about.cta.button': 'Get Started Today',
    // About Panel
    'panel.title': 'Discover Petra',
    'panel.about': 'About Us',
    'panel.whyPetra': 'Why Petra',
    'panel.governance': 'Corporate Governance',
    'panel.sustainability': 'Sustainability',
    // Why Petra Page
    'whyPetra.hero.title': 'Why Choose Petra?',
    'whyPetra.hero.subtitle': 'Your strategic partner in fuel solutions… where trust begins.',
    'whyPetra.strengths.label': 'Our Strengths',
    'whyPetra.strengths.title': 'Key Advantages',
    'whyPetra.strengths.professionalTeam.title': 'Professional Team',
    'whyPetra.strengths.professionalTeam.desc': 'Highly trained and certified professionals with extensive industry experience.',
    'whyPetra.strengths.customizedServices.title': 'Customized Services',
    'whyPetra.strengths.customizedServices.desc': 'Tailored solutions based on each client\'s unique needs and requirements.',
    'whyPetra.strengths.environmentalStandards.title': 'Environmental Standards',
    'whyPetra.strengths.environmentalStandards.desc': 'Full commitment to environmental regulations and sustainable practices.',
    'whyPetra.strengths.extensiveExperience.title': 'Extensive Experience',
    'whyPetra.strengths.extensiveExperience.desc': 'Years of proven expertise in storage and distribution operations.',
    'whyPetra.strengths.safetyInfrastructure.title': 'Safety Infrastructure',
    'whyPetra.strengths.safetyInfrastructure.desc': 'High-safety standard storage facilities with advanced protection systems.',
    'whyPetra.strengths.fmsSystem.title': 'FMS System',
    'whyPetra.strengths.fmsSystem.desc': 'Strategic Fuel Management System for optimal operational control.',
    'fms.label': 'Smart Technology',
    'fms.title': 'FMS Interactive Features',
    'fms.subtitle': 'Advanced fuel management system providing complete operational control and visibility.',
    'fms.lossPrevention.title': 'Loss Prevention',
    'fms.lossPrevention.leakDetection': 'Instant Leak Detection',
    'fms.lossPrevention.accessAlerts': 'Unauthorized Access Alerts',
    'fms.lossPrevention.userTracking': 'User-Tracked Withdrawals',
    'fms.dataAccuracy.title': 'Data Accuracy',
    'fms.dataAccuracy.sensorAccuracy': '99.9% Sensor Accuracy',
    'fms.dataAccuracy.detailedReports': 'Detailed Reporting',
    'fms.dataAccuracy.dataExports': 'Multi-Format Exports',
    'fms.realTimeMonitoring.title': 'Real-Time Monitoring',
    'fms.realTimeMonitoring.liveFuelLevels': 'Live Fuel Levels',
    'fms.realTimeMonitoring.remoteMonitoring': 'Remote Monitoring',
    'fms.realTimeMonitoring.autoAlerts': 'Auto Low-Level Alerts',
    'safetySystems.label': 'Protection Systems',
    'safetySystems.title': 'Safety Systems',
    'safetySystems.firefighting.title': 'Firefighting Systems',
    'safetySystems.firefighting.desc': 'Advanced fire suppression systems installed throughout all facilities.',
    'safetySystems.surveillance.title': 'HD Surveillance',
    'safetySystems.surveillance.desc': 'High-resolution cameras providing 24/7 monitoring coverage.',
    'safetySystems.extinguishers.title': 'Fire Extinguishers',
    'safetySystems.extinguishers.desc': 'Strategically placed extinguishers for rapid emergency response.',
    'vehicleControl.label': 'Facility Management',
    'vehicleControl.title': 'Vehicle & Facility Control',
    'vehicleControl.secureAccess.title': 'Secure Access',
    'vehicleControl.secureAccess.desc': 'Controlled vehicle entry with verification protocols.',
    'vehicleControl.monitoredEntry.title': 'Monitored Entry',
    'vehicleControl.monitoredEntry.desc': 'Real-time tracking of all entry and exit points.',
    'vehicleControl.waitingZones.title': 'Safe Waiting Zones',
    'vehicleControl.waitingZones.desc': 'Designated areas for safe vehicle staging.',
    'vehicleControl.trafficFlow.title': 'Intelligent Flow',
    'vehicleControl.trafficFlow.desc': 'Optimized traffic patterns for maximum efficiency.',
    'whyPetra.closing.text': 'We provide fully integrated logistics solutions where safety and efficiency come first…',
    'whyPetra.closing.signature': 'Petra — Your Trusted Partner',
    'pillars.label': 'Core Pillars',
    'pillars.title': 'What Drives Us',
    'pillars.technology.title': 'Advanced Technology',
    'pillars.technology.desc': 'Cutting-edge systems for optimal operations.',
    'pillars.safety.title': 'Safety Commitment',
    'pillars.safety.desc': 'Zero-compromise approach to safety standards.',
    'pillars.customer.title': 'Customer Focus',
    'pillars.customer.desc': 'Client satisfaction is our top priority.',
    'pillars.expertise.title': 'Fuel Expertise',
    'pillars.expertise.desc': 'Deep knowledge of the petroleum industry.',
  },
  ar: {
    'nav.home': 'الرئيسية', 'nav.services': 'الخدمات', 'nav.about': 'من نحن', 'nav.faq': 'الأسئلة الشائعة', 'nav.language': 'English',
    'hero.slide1.title': 'نقدم التميز في خدمات النفط وحلول الطاقة', 'hero.slide1.subtitle': 'تخزين متكامل، لوجستيات، واستشارات لقطاع النفط والغاز', 'hero.slide1.cta': 'ابدأ الآن',
    'hero.slide2.title': 'لماذا بترا؟', 'hero.slide2.subtitle': 'لأننا نجمع بين الخبرة العميقة والنزاهة التشغيلية والدقة', 'hero.slide2.cta': 'اكتشف السبب',
    'hero.slide3.title': 'الجودة والسلامة في كل عملية', 'hero.slide3.subtitle': 'نتبع معايير دولية صارمة لضمان الموثوقية والأداء الخالي من المخاطر', 'hero.slide3.cta': 'شاهد معاييرنا',
    'hero.slide4.title': 'انتشارنا، ميزتك', 'hero.slide4.subtitle': 'لوجستيات شاملة ومبادرات مستدامة عبر قطاع الطاقة', 'hero.slide4.cta': 'استكشف الخدمات',
    'quicklinks.faq.title': 'الأسئلة الشائعة', 'quicklinks.faq.desc': 'تعرف على المزيد حول خدماتنا وإجراءاتنا ومعايير السلامة.', 'quicklinks.faq.cta': 'عرض الأسئلة',
    'quicklinks.contact.title': 'تواصل معنا', 'quicklinks.contact.desc': 'فريقنا جاهز لمساعدتك. تواصل معنا للاستفسارات أو الشراكات.', 'quicklinks.contact.cta': 'تواصل الآن',
    'quicklinks.safety.title': 'السلامة والامتثال', 'quicklinks.safety.desc': 'نطبق إجراءات سلامة صارمة لضمان حماية الأشخاص والأصول والبيئة.', 'quicklinks.safety.cta': 'التزامنا بالسلامة',
    'services.title': 'خدمات مبتكرة تدعم مستقبل الطاقة', 'services.subtitle': 'حلول شاملة لقطاع الطاقة الحديث', 'services.cta.title': 'هل أنت مستعد لتحسين عمليات الطاقة؟', 'services.cta.button': 'اتصل بفريقنا',
    'detailed.storage.title': 'تخزين المشتقات البترولية', 'detailed.storage.desc': 'نوفر حلول تخزين آمنة وفعالة للبنزين والديزل والزيوت والمشتقات البترولية الأخرى. تشمل عملياتنا إدارة وصيانة خزانات التخزين وفقاً للمعايير الدولية.', 'detailed.storage.cta': 'اعرف المزيد',
    'detailed.logistics.title': 'إدارة سلسلة التوريد', 'detailed.logistics.desc': 'نخطط وننفذ حلول لوجستية متكاملة لنقل وتوزيع المشتقات البترولية. مصممة لتحسين شبكات التوزيع وتقليل التكاليف التشغيلية.', 'detailed.logistics.cta': 'استكشف اللوجستيات',
    'detailed.station.title': 'الاستثمار وتشغيل محطات الوقود', 'detailed.station.desc': 'دراسات جدوى لإنشاء وتطوير محطات الوقود في مواقع استراتيجية. خدمات تشغيل وإدارة كاملة تركز على الربحية طويلة المدى.', 'detailed.station.cta': 'شاهد الفرص',
    'detailed.consulting.title': 'الاستشارات الفنية والهندسية', 'detailed.consulting.desc': 'حلول استشارية متخصصة لتطوير البنية التحتية للنفط والغاز. تحليل السوق وتحديد فرص الاستثمار الجديدة.', 'detailed.consulting.cta': 'احصل على استشارة',
    'service.dropdown.storage': 'تخزين المنتجات البترولية', 'service.dropdown.logistics': 'إدارة سلسلة التوريد', 'service.dropdown.station': 'الاستثمار في محطات الوقود', 'service.dropdown.consulting': 'الاستشارات الفنية والهندسية',
    'about.title': 'من نحن', 'about.description': 'بترا شركة متخصصة في إدارة وتخزين ولوجستيات المشتقات البترولية. نعمل وفق معايير رائدة في الصناعة لضمان حلول طاقة آمنة وموثوقة.',
    'about.vision.title': 'رؤيتنا', 'about.vision.text': 'أن نكون الشريك الموثوق والرائد في خدمات لوجستيات وتخزين البترول.', 'about.mission.title': 'مهمتنا', 'about.mission.text': 'تقديم الطاقة بامتياز من خلال الابتكار والسلامة والكفاءة التشغيلية.',
    'about.values.title': 'قيمنا الأساسية', 'about.values.safety': 'السلامة', 'about.values.reliability': 'الموثوقية', 'about.values.integrity': 'النزاهة', 'about.values.sustainability': 'الاستدامة', 'about.values.excellence': 'التميز',
    'safety.title': 'السلامة أولاً. الجودة دائماً.', 'safety.description': 'نطبق معايير صارمة للصحة والسلامة والبيئة في كل مرحلة من عملياتنا.',
    'safety.hse': 'الصحة والسلامة والبيئة', 'safety.highlight1': 'الصيانة الوقائية والتحكم في المخاطر', 'safety.highlight2': 'الاستعداد للاستجابة للطوارئ', 'safety.highlight3': 'ممارسات حماية البيئة',
    'projects.title': 'سجلنا الحافل', 'projects.description': 'نفخر بتقديم حلول لوجستية وتخزين ناجحة لمختلف العملاء الاستراتيجيين في قطاع النفط والغاز.',
    'projects.stats.years': 'سنوات من الخبرة', 'projects.stats.clients': 'عملاء راضون', 'projects.stats.locations': 'مواقع الخدمة', 'projects.stats.certifications': 'الشهادات',
    'projects.project1.tag': 'تخزين', 'projects.project1.title': 'منشأة تخزين إقليمية', 'projects.project1.desc': 'منشأة تخزين بترول حديثة بسعة تزيد عن 50,000 برميل.',
    'projects.project2.tag': 'لوجستيات', 'projects.project2.title': 'مشروع تحسين الأسطول', 'projects.project2.desc': 'إصلاح لوجستي شامل قلل أوقات التسليم بنسبة 40%.',
    'projects.project3.tag': 'استثمار', 'projects.project3.title': 'محطات وقود خضراء', 'projects.project3.desc': 'شبكة محطات وقود تعمل بالطاقة الشمسية.',
    'contact.title': 'تواصل معنا', 'contact.description': 'فريقنا جاهز لدعم احتياجاتك. تواصل معنا للاستفسارات التجارية أو مقترحات الخدمات.',
    'contact.form.name': 'الاسم الكامل', 'contact.form.email': 'البريد الإلكتروني', 'contact.form.phone': 'رقم الهاتف', 'contact.form.message': 'رسالتك', 'contact.form.submit': 'إرسال الرسالة', 'contact.form.success': 'تم إرسال الرسالة!', 'contact.form.successDesc': 'سنتواصل معك قريباً.',
    'contact.info.phone': 'الهاتف', 'contact.info.email': 'البريد الإلكتروني', 'contact.info.address': 'العنوان', 'contact.info.hours': 'ساعات العمل', 'contact.map.placeholder': 'خريطة الموقع',
    'cta.title': 'شاركنا لتشكيل مستقبل الطاقة', 'cta.description': 'هل أنت مستعد للارتقاء بعملياتك في مجال الطاقة؟', 'cta.button1': 'اطلب عرض سعر', 'cta.button2': 'اعرف المزيد',
    'faq.title': 'الأسئلة الشائعة', 'faq.subtitle': 'اعثر على إجابات للأسئلة الشائعة حول خدماتنا.',
    'faq.q1': 'ما هي الخدمات التي تقدمها بترا؟', 'faq.a1': 'تقدم بترا خدمات بترولية شاملة تشمل حلول التخزين وإدارة سلسلة التوريد والاستثمار وتشغيل محطات الوقود.',
    'faq.q2': 'ما هي معايير السلامة التي تتبعونها؟', 'faq.a2': 'نلتزم بمعايير صارمة للصحة والسلامة والبيئة الدولية.',
    'faq.q3': 'أين تتوفر خدماتكم؟', 'faq.a3': 'خدماتنا متاحة في جميع أنحاء الأردن ومنطقة الشرق الأوسط.',
    'faq.q4': 'كيف يمكنني طلب عرض سعر؟', 'faq.a4': 'يمكنك طلب عرض سعر من خلال ملء نموذج الاتصال أو الاتصال بمكتبنا مباشرة.',
    'faq.q5': 'هل تقدمون فرص شراكة؟', 'faq.a5': 'نعم، نسعى بنشاط للشراكات الاستراتيجية مع الشركات في قطاع النفط والغاز.',
    'faq.q6': 'ما الذي يميز بترا عن المنافسين؟', 'faq.a6': 'تجمع بترا بين الخبرة العميقة في الصناعة والنزاهة التشغيلية والحلول المبتكرة.',
    'footer.description': 'متخصصون في إدارة وتخزين ولوجستيات المشتقات البترولية.', 'footer.quickLinks': 'روابط سريعة', 'footer.services': 'خدماتنا', 'footer.contact': 'معلومات الاتصال',
    'footer.links.home': 'الرئيسية', 'footer.links.services': 'الخدمات', 'footer.links.about': 'من نحن', 'footer.links.contact': 'اتصل بنا', 'footer.rights': 'جميع الحقوق محفوظة.',
    // About Page
    'about.hero.title': 'بيترا — القوة… الصلابة… الثبات في عالم الطاقة',
    'about.hero.subtitle': 'شركة رائدة في حلول تخزين ونقل المشتقات النفطية والخدمات الاستشارية.',
    'about.hero.cta1': 'تواصل معنا',
    'about.hero.cta2': 'خدماتنا',
    'about.section.label': 'من نحن',
    'about.section.title': 'تعرف علينا',
    'about.section.paragraph1': 'كلمة بيترا تعني "الصخرة" في اليونانية القديمة، ترمز إلى القوة والصلابة والصبر والثبات. شركة بيترا لخدمات النفط هي شركة رائدة في قطاع النفط والطاقة، تقدم خبرة واسعة في توفير حلول متكاملة للتخزين والنقل والاستشارات.',
    'about.section.paragraph2': 'يشمل نطاق عمل الشركة استشارات النفط والغاز، تخزين ونقل المنتجات البترولية (براً وبحراً)، الاستثمار وإعادة تأهيل محطات الوقود، توريد وتركيب أنظمة الوقود، والخدمات المتنوعة المتعلقة بصناعة النفط والغاز.',
    'timeline.label': 'مسيرتنا',
    'timeline.title': 'الجدول الزمني للشركة',
    'timeline.2019': 'تأسيس الشركة في السوق المحلي. التخطيط الاستراتيجي وتطوير البنية التحتية. الحصول على التراخيص المطلوبة وتشكيل فريق متخصص.',
    'timeline.2020': 'التوسع الاستراتيجي ومضاعفة سعة التخزين. تحسينات الكفاءة التشغيلية وتدريب القوى العاملة.',
    'timeline.2022': 'تطبيق تقنيات المراقبة المتقدمة. اعتماد نظام إدارة الوقود (FMS). تحقيق سجلات سلامة عالية والتميز التشغيلي.',
    'timeline.2024': 'تعزيز مكانة الشركة كرائدة في حلول الوقود. التوسع في خدمات الاستشارات النفطية. بناء سمعة سوقية قوية كشريك موثوق.',
    'timeline.2025': 'الحصول على شهادات الجودة الدولية: ISO 9001 و ISO 29001.',
    'vision.title': 'رؤيتنا',
    'vision.text': 'أن نصبح المزود الرائد لخدمات المشتقات البترولية من خلال تقديم حلول عالية الجودة تدعم استدامة الطاقة وتتجاوز توقعات العملاء.',
    'mission.title': 'مهمتنا',
    'mission.text': 'توفير حلول تخزين وخدمات آمنة وفعالة للمنتجات البترولية مع الحفاظ على أعلى معايير الجودة والسلامة والاستدامة البيئية.',
    'scope.label': 'ماذا نفعل',
    'scope.title': 'نطاق العمل',
    'scope.storage.title': 'تخزين البترول',
    'scope.storage.desc': 'حلول تخزين آمنة وفعالة للبنزين والديزل والزيوت والمنتجات الأخرى. تشغيل وإدارة خزانات التخزين وفقاً للمعايير العالمية. تقنيات مراقبة المخزون وتقليل الفاقد.',
    'scope.logistics.title': 'إدارة سلسلة التوريد',
    'scope.logistics.desc': 'تخطيط وتنفيذ اللوجستيات المتكاملة لتوزيع المنتجات البترولية. تحسين شبكات التوزيع لتقليل التكاليف وتحسين الكفاءة. إدارة علاقات الموردين والعملاء لضمان استمرارية التوريد.',
    'scope.station.title': 'الاستثمار في محطات الوقود',
    'scope.station.desc': 'دراسات جدوى لمحطات الوقود الجديدة أو القائمة. التشغيل والإدارة بمعايير ربحية عالية. تطوير حلول الطاقة البديلة مثل أنظمة الطاقة الشمسية.',
    'scope.consulting.title': 'الخدمات الفنية والاستشارية',
    'scope.consulting.desc': 'الاستشارات الهندسية والفنية لمشاريع النفط والغاز. تحليل السوق ودراسات فرص الاستثمار. تدريب الفرق على أفضل ممارسات الصناعة والتميز التشغيلي.',
    'values.label': 'ما نؤمن به',
    'values.title': 'قيمنا',
    'values.comprehensive': 'الالتزام بتقديم حلول تخزين وتوزيع بترولية شاملة ومتكاملة.',
    'values.technology': 'استخدام التقنيات المتقدمة وأفضل الممارسات العالمية لتحقيق أقصى جودة وكفاءة.',
    'values.safety': 'الالتزام بأعلى معايير السلامة والجودة.',
    'values.improvement': 'التحسين المستمر من خلال فرق الخبراء وفهم السوق المتطور.',
    'values.innovation': 'تقديم حلول مبتكرة تلبي وتتجاوز توقعات العملاء.',
    'about.cta.title': 'هل أنت مستعد للشراكة معنا؟',
    'about.cta.description': 'دعنا نساعدك على تحقيق التميز في تخزين ولوجستيات واستشارات البترول.',
    'about.cta.button': 'ابدأ اليوم',
    // About Panel
    'panel.title': 'اكتشف بترا',
    'panel.about': 'من نحن',
    'panel.whyPetra': 'لماذا بترا',
    'panel.governance': 'الحوكمة المؤسسية',
    'panel.sustainability': 'الاستدامة',
    // Why Petra Page
    'whyPetra.hero.title': 'لماذا تختار بترا؟',
    'whyPetra.hero.subtitle': 'شريكك الاستراتيجي في حلول الوقود… حيث تبدأ الثقة.',
    'whyPetra.strengths.label': 'نقاط قوتنا',
    'whyPetra.strengths.title': 'المزايا الرئيسية',
    'whyPetra.strengths.professionalTeam.title': 'فريق محترف',
    'whyPetra.strengths.professionalTeam.desc': 'متخصصون مدربون ومعتمدون بخبرة واسعة في الصناعة.',
    'whyPetra.strengths.customizedServices.title': 'خدمات مخصصة',
    'whyPetra.strengths.customizedServices.desc': 'حلول مصممة بناءً على احتياجات ومتطلبات كل عميل.',
    'whyPetra.strengths.environmentalStandards.title': 'المعايير البيئية',
    'whyPetra.strengths.environmentalStandards.desc': 'التزام كامل باللوائح البيئية والممارسات المستدامة.',
    'whyPetra.strengths.extensiveExperience.title': 'خبرة واسعة',
    'whyPetra.strengths.extensiveExperience.desc': 'سنوات من الخبرة المثبتة في عمليات التخزين والتوزيع.',
    'whyPetra.strengths.safetyInfrastructure.title': 'بنية السلامة',
    'whyPetra.strengths.safetyInfrastructure.desc': 'مرافق تخزين عالية الأمان مع أنظمة حماية متقدمة.',
    'whyPetra.strengths.fmsSystem.title': 'نظام FMS',
    'whyPetra.strengths.fmsSystem.desc': 'نظام إدارة الوقود الاستراتيجي للتحكم التشغيلي الأمثل.',
    'fms.label': 'التكنولوجيا الذكية',
    'fms.title': 'مميزات نظام FMS التفاعلية',
    'fms.subtitle': 'نظام إدارة وقود متقدم يوفر تحكمًا ورؤية تشغيلية كاملة.',
    'fms.lossPrevention.title': 'منع الفقد',
    'fms.lossPrevention.leakDetection': 'كشف التسرب الفوري',
    'fms.lossPrevention.accessAlerts': 'تنبيهات الوصول غير المصرح',
    'fms.lossPrevention.userTracking': 'تتبع عمليات السحب',
    'fms.dataAccuracy.title': 'دقة البيانات',
    'fms.dataAccuracy.sensorAccuracy': 'دقة المستشعرات 99.9%',
    'fms.dataAccuracy.detailedReports': 'تقارير مفصلة',
    'fms.dataAccuracy.dataExports': 'تصدير متعدد الصيغ',
    'fms.realTimeMonitoring.title': 'المراقبة الحية',
    'fms.realTimeMonitoring.liveFuelLevels': 'مستويات الوقود الحية',
    'fms.realTimeMonitoring.remoteMonitoring': 'المراقبة عن بعد',
    'fms.realTimeMonitoring.autoAlerts': 'تنبيهات انخفاض المستوى',
    'safetySystems.label': 'أنظمة الحماية',
    'safetySystems.title': 'أنظمة السلامة',
    'safetySystems.firefighting.title': 'أنظمة مكافحة الحرائق',
    'safetySystems.firefighting.desc': 'أنظمة إطفاء متقدمة مثبتة في جميع المرافق.',
    'safetySystems.surveillance.title': 'مراقبة عالية الدقة',
    'safetySystems.surveillance.desc': 'كاميرات عالية الدقة توفر تغطية مراقبة على مدار الساعة.',
    'safetySystems.extinguishers.title': 'طفايات الحريق',
    'safetySystems.extinguishers.desc': 'طفايات موزعة استراتيجياً للاستجابة السريعة للطوارئ.',
    'vehicleControl.label': 'إدارة المرافق',
    'vehicleControl.title': 'التحكم في المركبات والمرافق',
    'vehicleControl.secureAccess.title': 'دخول آمن',
    'vehicleControl.secureAccess.desc': 'دخول مركبات متحكم به مع بروتوكولات التحقق.',
    'vehicleControl.monitoredEntry.title': 'دخول مراقب',
    'vehicleControl.monitoredEntry.desc': 'تتبع حي لجميع نقاط الدخول والخروج.',
    'vehicleControl.waitingZones.title': 'مناطق انتظار آمنة',
    'vehicleControl.waitingZones.desc': 'مناطق مخصصة لوقوف المركبات الآمن.',
    'vehicleControl.trafficFlow.title': 'تدفق ذكي',
    'vehicleControl.trafficFlow.desc': 'أنماط حركة مرور محسنة لأقصى كفاءة.',
    'whyPetra.closing.text': 'نقدم حلول لوجستية متكاملة حيث تأتي السلامة والكفاءة أولاً…',
    'whyPetra.closing.signature': 'بترا — شريكك الموثوق',
    'pillars.label': 'الركائز الأساسية',
    'pillars.title': 'ما يحركنا',
    'pillars.technology.title': 'تكنولوجيا متقدمة',
    'pillars.technology.desc': 'أنظمة متطورة لعمليات مثالية.',
    'pillars.safety.title': 'التزام بالسلامة',
    'pillars.safety.desc': 'نهج بدون تنازل لمعايير السلامة.',
    'pillars.customer.title': 'التركيز على العميل',
    'pillars.customer.desc': 'رضا العميل هو أولويتنا القصوى.',
    'pillars.expertise.title': 'خبرة الوقود',
    'pillars.expertise.desc': 'معرفة عميقة بصناعة البترول.',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('petra-language');
    return (saved === 'ar' || saved === 'en') ? saved : 'en';
  });

  useEffect(() => {
    localStorage.setItem('petra-language', language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const setLanguage = (lang: Language) => setLanguageState(lang);
  const t = (key: string): string => translations[language][key as keyof typeof translations['en']] || key;
  const dir = language === 'ar' ? 'rtl' : 'ltr';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
};
